import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Interactive Hand Particle Art",
  description: "Generated by Gemini 3D",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="bg-black text-white overflow-hidden antialiased touch-none">
        {children}
      </body>
    </html>
  );
}
